server:
  port: 10030

spring:
  application:
    name: gulimall-member

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.150:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.150:8848
        namespace: 5bb7d83e-c429-49a4-8200-ea796f91b6f1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.150
    port: 6379



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


#logging:
#  level:
#    com.atguigu.gulimall: debug




