#server:
#  port: 10010

spring:
#  application:
#    name: gulimall-coupon
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.150:3306/gulimall_pms
#    driver-class-name: com.mysql.cj.jdbc.Drive

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.1.150:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.150
    port: 6379



#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0


#logging:
#  level:
#    com.atguigu.gulimall: debug




